/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AuthedAccountsRouteImport } from './routes/_authed/accounts'
import { Route as AuthedHomeRouteImport } from './routes/_authed/home'
import { Route as AuthSignOutRouteImport } from './routes/auth/sign-out'
import { Route as AuthedProfileIndexRouteImport } from './routes/_authed/profile/index'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'
import { Route as AuthGoogleStartRouteImport } from './routes/auth/google/start'
import { Route as DevDesignIndexRouteImport } from './routes/dev/design/index'
import { Route as DevDesignFrameRouteImport } from './routes/dev/design/frame'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAccountsRoute = AuthedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHomeRoute = AuthedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthSignOutRoute = AuthSignOutRouteImport.update({
  id: '/auth/sign-out',
  path: '/auth/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProfileIndexRoute = AuthedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleStartRoute = AuthGoogleStartRouteImport.update({
  id: '/auth/google/start',
  path: '/auth/google/start',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDesignIndexRoute = DevDesignIndexRouteImport.update({
  id: '/dev/design/',
  path: '/dev/design/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDesignFrameRoute = DevDesignFrameRouteImport.update({
  id: '/dev/design/frame',
  path: '/dev/design/frame',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/accounts': typeof AuthedAccountsRoute
  '/home': typeof AuthedHomeRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/start': typeof AuthGoogleStartRoute
  '/dev/design/frame': typeof DevDesignFrameRoute
  '/profile/': typeof AuthedProfileIndexRoute
  '/dev/design/': typeof DevDesignIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/accounts': typeof AuthedAccountsRoute
  '/home': typeof AuthedHomeRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/start': typeof AuthGoogleStartRoute
  '/dev/design/frame': typeof DevDesignFrameRoute
  '/profile': typeof AuthedProfileIndexRoute
  '/dev/design': typeof DevDesignIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/signin': typeof SigninRoute
  '/_authed/accounts': typeof AuthedAccountsRoute
  '/_authed/home': typeof AuthedHomeRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/start': typeof AuthGoogleStartRoute
  '/dev/design/frame': typeof DevDesignFrameRoute
  '/_authed/profile/': typeof AuthedProfileIndexRoute
  '/dev/design/': typeof DevDesignIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/accounts'
    | '/home'
    | '/auth/sign-out'
    | '/auth/google/callback'
    | '/auth/google/start'
    | '/dev/design/frame'
    | '/profile/'
    | '/dev/design/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/accounts'
    | '/home'
    | '/auth/sign-out'
    | '/auth/google/callback'
    | '/auth/google/start'
    | '/dev/design/frame'
    | '/profile'
    | '/dev/design'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/signin'
    | '/_authed/accounts'
    | '/_authed/home'
    | '/auth/sign-out'
    | '/auth/google/callback'
    | '/auth/google/start'
    | '/dev/design/frame'
    | '/_authed/profile/'
    | '/dev/design/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  SigninRoute: typeof SigninRoute
  AuthSignOutRoute: typeof AuthSignOutRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  AuthGoogleStartRoute: typeof AuthGoogleStartRoute
  DevDesignFrameRoute: typeof DevDesignFrameRoute
  DevDesignIndexRoute: typeof DevDesignIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/accounts': {
      id: '/_authed/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthedAccountsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/home': {
      id: '/_authed/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthedHomeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/sign-out': {
      id: '/auth/sign-out'
      path: '/auth/sign-out'
      fullPath: '/auth/sign-out'
      preLoaderRoute: typeof AuthSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/profile/': {
      id: '/_authed/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthedProfileIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/start': {
      id: '/auth/google/start'
      path: '/auth/google/start'
      fullPath: '/auth/google/start'
      preLoaderRoute: typeof AuthGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/design/': {
      id: '/dev/design/'
      path: '/dev/design'
      fullPath: '/dev/design/'
      preLoaderRoute: typeof DevDesignIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/design/frame': {
      id: '/dev/design/frame'
      path: '/dev/design/frame'
      fullPath: '/dev/design/frame'
      preLoaderRoute: typeof DevDesignFrameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedAccountsRoute: typeof AuthedAccountsRoute
  AuthedHomeRoute: typeof AuthedHomeRoute
  AuthedProfileIndexRoute: typeof AuthedProfileIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountsRoute: AuthedAccountsRoute,
  AuthedHomeRoute: AuthedHomeRoute,
  AuthedProfileIndexRoute: AuthedProfileIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SigninRoute: SigninRoute,
  AuthSignOutRoute: AuthSignOutRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  AuthGoogleStartRoute: AuthGoogleStartRoute,
  DevDesignFrameRoute: DevDesignFrameRoute,
  DevDesignIndexRoute: DevDesignIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
