CREATE TABLE winston.artifact_transfers (
  owner_id uuid NOT NULL,
  id uuid NOT NULL,
  action_id uuid NOT NULL,
  task_id uuid NOT NULL,
  intent_revision integer NOT NULL,
  workspace_id uuid NOT NULL,
  artifact_id uuid NOT NULL,
  request_key text NOT NULL,
  state text NOT NULL DEFAULT 'pending' CHECK (state IN ('pending', 'active', 'unknown', 'staged')),
  token_hash text UNIQUE,
  source_capability_id uuid,
  expires_at timestamptz,
  descriptor jsonb,
  receipt jsonb,
  PRIMARY KEY (owner_id, id),
  UNIQUE (owner_id, request_key),
  UNIQUE (owner_id, action_id),
  FOREIGN KEY (owner_id, action_id) REFERENCES winston.actions(owner_id, id),
  FOREIGN KEY (owner_id, task_id) REFERENCES winston.tasks(owner_id, id),
  FOREIGN KEY (owner_id, workspace_id) REFERENCES winston.workspaces(owner_id, id),
  FOREIGN KEY (owner_id, artifact_id) REFERENCES winston.artifacts(owner_id, id),
  FOREIGN KEY (owner_id, source_capability_id) REFERENCES winston.service_capabilities(owner_id, id),
  CHECK (intent_revision >= 0),
  CHECK (state <> 'active' OR (token_hash IS NOT NULL AND source_capability_id IS NOT NULL AND expires_at IS NOT NULL AND descriptor IS NOT NULL)),
  CHECK (state <> 'staged' OR receipt IS NOT NULL)
);
