import ProxyState

var state = ProxyState()
precondition(!state.acceptsActions && state.label == "Disconnected")
state.setConnection(.connecting)
precondition(!state.acceptsActions)
state.setConnection(.connected)
precondition(state.acceptsActions && state.label == "Connected")
state.setPaused(true)
state.setConnection(.connected)
precondition(!state.acceptsActions && state.label == "Paused")
state.sleep()
state.wake()
precondition(state.isPaused && !state.acceptsActions)
state.setPaused(false)
precondition(!state.acceptsActions && state.connection == .disconnected)
state.setConnection(.connected)
precondition(state.acceptsActions)
state.sleep()
precondition(!state.acceptsActions && state.label == "Sleeping")
state.wake()
precondition(!state.acceptsActions && state.label == "Disconnected")
print("Native shell lifecycle checks passed")
